name: Makefile CI

on:
  workflow_dispatch:
  push:
    tags:        
      - v*.**
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: echo
      run: echo ${{ github.event_name}} ${{github.event.action}}
