name: Makefile CI

on:
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Install python dependencies
      run: pip install -r requirements.txt
      
    - name: Download article data & reformat to delimited datafiles
      run: make all

    - name: Attach built artifact to run 
      uses: actions/upload-artifact@v3
      with:
        name: data
        path: data
